document.getElementById("findId").addEventListener("click",()=>{
  location.href="./findIdPage.jsp"
})
document.getElementById("findPw").addEventListener("click",()=>{
  location.href="./findPwPage.jsp"
})
document.getElementById("signUp").addEventListener("click",()=>{
  location.href="./signUpPage.jsp"
})
document.getElementById("login").addEventListener("click",()=>{
  location.href="./schedulePage.jsp"
})
